[phases.setup]
nixPkgs = ['bun', 'nodejs_24']

[phases.setup.env]
NIXPKGS_ALLOW_UNFREE = "1"

[phases.install]
cmds = ['corepack enable && corepack prepare pnpm@10.20.0 --activate && pnpm install']

[phases.build]
cmds = ['NODE_OPTIONS="--max-old-space-size=8192" pnpm run build']

[start]
cmd = "pnpm start"
